[package]
name = "loxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"
mimalloc = "0.1.30"

[features]
default = []
debug_gc = []
always_gc = []
